name: Deploy Next.js MyWallet to VPS InterServer

on:
  push:
    branches:
      - master # Dispara o deploy sempre que você der push na branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 24 # Escolha a mesma versão do seu CloudPanel
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy to VPS via SFTP (SSH)
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlgoDzvc --delete" # Sincroniza os arquivos de forma otimizada
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: /home/my-wallet/htdocs/my.wallet.local/ # O caminho correto do seu VPS
          SOURCE: ./ # Envia tudo da raiz compilada
          EXCLUDE: |
            /.git/
            /node_modules/
            /src/
            /app/
            /pages/
            /components/
            /dev/
