- name: Deploy Next.js MyWallet to VPS via SFTP (SSH)
  uses: easingthemes/ssh-deploy@v5.1.0
  with:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
    ARGS: "-rlgoDzvc --delete" # Sincroniza os arquivos de forma otimizada
    REMOTE_HOST: ${{ secrets.SSH_HOST }}
    REMOTE_USER: ${{ secrets.SSH_USER }}
    TARGET: /home/my-wallet/htdocs/my.wallet.local/ # O caminho correto do seu VPS
    SOURCE: ./ # Envia tudo da raiz compilada
    EXCLUDE: |
      /.git/
      /node_modules/
      /src/
      /app/
      /pages/
      /components/
